Quotes1 = {1:'Язык программирования:computer::computer::computer: "Пыхтон":dash::dash::snake:научит молодых нормальной забибовчке:muscle::muscle:Надеюсь, программисты:pager: уже скоро сделают калик с автозабивкой дабл эппл:green_apple::apple:(dvoynoye yabloko):sunglasses::call_me::sunglasses::call_me:',
           2:'Программисты шалят :call_me_tone1: :smiling_imp:А че, айтишники тоже непрочь календулу с кралями раздуть) Вы не думайте, что это задроты:joy: :school: Они такую забивку намешают, что любая краля офигеет:dizzy_face: :dash: :lips: Им только повод дай) А там уж и «Питона» своего покажут, да «СиСи++», если вы понимаете о чем я:rofl: :thumbsup_tone1: :underage: Кальянчик  всех радует: и качков, и очкариков) Главное дуть с кайфом пацаны:point_up_tone1: И неважно, какой ты национальности:blush:',
           3:'Вот это Икс-колюмбокс :flushed::scream_cat: Сразу видно Фил (Spencer) долго готовил забивку :drooling_face: Выбирая самые спелые :lips:, самые сочные :heart_eyes:, самые наливные :green_apple::apple: (dvoynie yabloki)На такую X-коробку любая краля :dancer::heart: прибежит и вдохнет дым через мундштучеллу :stuck_out_tongue_winking_eye: по самые гланды :drooling_face::underage:Чтите традиции :point_up_tone1: Не поддавайтесь на уловки :triumph: грязных (dirty) сонибоев :nauseated_face::face_with_symbols_over_mouth:Помните братья, что наш РУССКИЙ :flag_mu: Пыхфуций :man_wearing_turban: говорил:Если калик покурил - ты у краль :lips: номер один :sun_with_face::heart_eyes:Если братик плейстейшон :nauseated_face: взял, то считай пропал пацан :chicken::blue_heart:Всем братьям peace :right_facing_fist_tone1::left_facing_fist_tone1:, всем кралям kiss :revolving_hearts:',
           4:'Киберпыхи здесь? :sunglasses: :sunglasses: :sunglasses: Будущее будущим, но как в 2077 без хорошего кумарика? :thought_balloon: :thought_balloon: :thought_balloon: Вот и поляки так думают, поэтому добавили такого красавца в Найт-Сити :night_with_stars: :night_with_stars: :night_with_stars: Как известно, в голове главного героя сидит Киану Ривз :star2: :star2: :star2: , а точнее его персонаж - Джонни Сильверпых :dash: :dash: :dash: Он то нам и посоветует лучшую киберзабивочку и устроит колюмбас будущего :fire: :fire: :fire: Как угля нет? :scream_cat: :scream_cat: :scream_cat: Очередной баг :warning: :warning: :warning: Недоглядели игроделы :ghost: :ghost: :ghost: Ну ничего, прощаем :call_me: :call_me: :call_me: Игру ждали - и обновлений дождемся :hourglass: :hourglass: :hourglass:  Всем геймерам крутых кумарочных имплантов и качественного пыха в виртуальном мире :thumbsup: :thumbsup: :thumbsup: :metal: :metal: :call_me:',
           }

links = {1:'https://tenor.com/view/no-genshin-impact-discord-rules-gif-20700280',
         2:'https://tenor.com/view/davy-enardo-discord-gif-19344074',
         3:'https://discord.com/channels/695715313911857186/883030868321505300/883031033216385065',
         4:'https://tenor.com/view/dimden-dimdem-discord-rules-discord-meme-gif-22604752',
         5:'https://tenor.com/view/rule5-rule-dominic-bully-no_bully-gif-20706308',
         6:'https://tenor.com/view/goku-rule6-discord-dbz-gif-22504372',
         7:'https://tenor.com/view/bruh-gif-19222296',
         8:'https://tenor.com/view/davy-enardo-discord-gif-19344047',
         9:'https://tenor.com/view/discord-rules-rules-gif-18972022',
         10:'https://tenor.com/view/dimden-cat-dimdem-cute-cat-discord-gif-22604911',
         11:'https://tenor.com/view/rule-rule11-11-gif-21694891',
         12:'https://tenor.com/view/people-playground-rule12-gif-20419176',
         13:'https://tenor.com/view/1984-rule13-gif-21572417',
         14:'https://tenor.com/view/yohane-tsushima-yoshiko-love-live-llas-sifas-gif-22897501',
         15:'https://tenor.com/view/rule15-no-catgirls-gif-22773712',
         16:'https://tenor.com/view/discord-moderator-discord-muscle-rules-gif-19567985',
         17:'https://tenor.com/view/cringetopia-rule17-gif-20201346',
         18:'https://tenor.com/view/passione-admin-passione-jojolion-gif-19246434',
         19:'https://tenor.com/view/icefuse-rules-rule19-icefuse-gif-20831151',
         20:'https://tenor.com/view/rule-20-stop-saying-im-gif-20469427',
         21:'https://tenor.com/view/rule-21-rule21-gif-21971935',
         22:'https://tenor.com/view/monkey-gif-21560751',
         23:'https://tenor.com/view/jaxon-manda-twerk-gif-22390113',
         24:'https://tenor.com/view/ben-shapiro-rule24-gif-21884410',
         25:'https://tenor.com/view/no-wa-gif-21166953',
         26:'https://tenor.com/view/curtain-lonnie-howwie-discord-rules-lon-gif-22730453',
         27:'https://tenor.com/view/rule27-gif-21989177',
         28:'https://tenor.com/view/sussy-faxball-gif-21459760',
         29:'@dani4feedyt#5200 попрохав не відображати це правило...',
         30:'https://tenor.com/view/rule-rule30-shut-up-monster-dragging-gif-22280127',
         31:'https://tenor.com/view/rule31-minecraft-dungeons-gif-22630176',
         32:'https://cdn.discordapp.com/attachments/883030868321505300/891755183963504650/ezgif.com-gif-maker.gif',
         33:'https://cdn.discordapp.com/attachments/883030868321505300/891758964415545384/voevoda.gif',
         34:'https://tenor.com/view/giga-chad-gif-23044971',
        }
