version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: banderabot-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  discord-bot:
    build: .
    container_name: banderabot
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    restart: always

volumes:
  pgdata: