name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Mark repo as safe directory
        run: git config --global --add safe.directory /mnt/Pull1/Scripts/banderabot

      - name: Reset local changes
        run: |
          cd /mnt/Pull1/Scripts/banderabot
          git reset --hard
          git clean -fd  

      - name: Pull latest changes in local repo
        run: |
          cd /mnt/Pull1/Scripts/banderabot
          git pull origin main

      - name: Build and restart bot container
        run: |
           /mnt/Pull1/Scripts/docker-compose -f /mnt/Pull1/Scripts/banderabot/docker-compose.yml down
           /mnt/Pull1/Scripts/docker-compose -f /mnt/Pull1/Scripts/banderabot/docker-compose.yml up -d --build